name: input_mahasiswa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  path: ^1.8.2

flutter:
  uses-material-design: true
